---
- name: Create Security Rule
  panos_security_rule:
    ip_address: "{{ firewall_node }}"
    username: "{{ paloalto_username }}"
    password: "{{ paloalto_password }}"
    operation: 'add'
    rule_name: "{{ firewall_rule_name }}"
    description: 'Ansible Demo'
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ dest_zone }}"
    source_ip: "{{ srcip }}"
    source_user: ['any']
    destination_ip: "{{ destip }}"
    category: ['any']
    application: "{{ application }}"
    service: ['application-default']
    hip_profiles: ['any']
    action: "{{ action }}"
    commit: 'False'