---
- name: Create Security Rule
  panos_security_rule:
    ip_address: "{{ firewall_node }}"
    username: "{{ paloalto_username }}"
    password: "{{ paloalto_password }}"
    operation: 'add'
    rule_name: 'Ansible test 1'
    description: 'An Ansible test rule'
    source_zone: ['internal']
    destination_zone: ['external']
    source_ip: ['1.2.3.4']
    source_user: ['any']
    destination_ip: ['any']
    category: ['any']
    application: ['any']
    service: ['service-http']
    hip_profiles: ['any']
    action: 'allow'
    commit: 'False'